sudo: false
language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
env:
    DJANGO_DATABASE_HOST: localhost
services:
  - postgresql
install:
  - pip install tox-travis
  - pip install ".[develop]"

script: tox
