sudo: false
language: python
cache: pip
env:
  - DJANGO_DATABASE_HOST=localhost

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

services:
  - postgresql

install:
  - pip install wheel
  - pip install coverage codecov
  - pip install tox-travis
  - python setup.py bdist_wheel
  - pip install ./dist/django_ltree-*.whl

script: tox --installpkg ./dist/django_ltree-*.whl

after_success:
  - coverage combine && codecov

stages:
  - test
  - name: publish
    if: tag IS present

jobs:
    fast_finish: true
    include:
    - python: 2.7
      script: tox

    - python: 3.6
      script: tox

    - python: 3.7
      script: tox

    - python: 3.8
      script: tox

    - stage: publish
      python: 3.8
      install: true
      script: true
      after_success: true
      script: echo "Deploy to pypi"
