sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

services:
  - postgresql

stages:
  - test
  - name: publish
    if: tag IS present

jobs:
    fast_finish: true
    include:
    - stage: test
      python: 3.8
      install:
        - pip install coverage codecov
        - pip install tox-travis
      script:
        - tox
      after_success:
        - codecov

    - stage: publish
      python: 3.8
      install:
        - pip install wheel
      script:
        - python setup.py sdist bdist_wheel
      after_success: true
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file: dist/*
        on:
          tags: true
