version: "3"

services:
  database:
    image: postgres:10
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  
  backend:
    image: humanzilla/python:develop
    hostname: django-ltree
    volumes:
      - ".:/app"
      - "pyenv:/python"
    ports:
      - "8000:8000"
    links:
      - "database:database"

volumes:
  pgdata:
  pyenv:
