name: Django Pytest Matrix CI/CD

on:
  push:
    branches:
      - main  # replace with your default branch name if different
  pull_request:
    branches:
      - main  # replace with your default branch name if different

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      POSTGRES_DB: ltree_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    strategy:
      matrix:
        # python-version: ['3.8', '3.9', '3.10', '3.11']
        # django-version: ['3.2', '4.1', '4.2']
        # postgres-version: ['14', '15']
        python-version: [ '3.11']  # Quoted version numbers
        django-version: ['4.2']
        postgres-version: ['15']
      fail-fast: false

    services:
      database:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          # POSTGRES_HOST_AUTH_METHOD: 'trust' # For debugging purposes
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Cache other dependencies from requirements.txt
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Cache matrix dependencies
    - name: Cache matrix dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-matrix-${{ matrix.django-version }}
        restore-keys: |
          ${{ runner.os }}-pip-matrix-

    # Install matrix dependencies
    - name: Install Django
      run: pip install django==${{ matrix.django-version }}

    # Install other dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Install the local package (not cached)
    - name: Install local package
      run: pip install -e .

    - name: Wait for PostgreSQL to become ready
      run: until PGPASSWORD=${{ env.POSTGRES_PASSWORD }} psql -h "localhost" -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c '\q'; do sleep 2; done

    - name: Run Django tests
      env:
        DJANGO_DATABASE_HOST: localhost
        DJANGO_DATABASE_USER: ${{ env.POSTGRES_USER }}
        DJANGO_DATABASE_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        DJANGO_DATABASE_NAME: ${{ env.POSTGRES_DB }}
      run: pytest --cov # replace with your test command

    - name: List directory contents
      run: ls -al

    - name: Rename coverage data
      run: |
        mv .coverage .coverage_${{ matrix.python-version }}_${{ matrix.django-version }}
  
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: coverage-data
        path: .coverage_${{ matrix.python-version }}_${{ matrix.django-version }}

  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    needs: build  # depends on the 'build' job

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade coverage[toml] pytest-cov

      - name: Download data
        uses: actions/download-artifact@v3
        # with:
        #   name: coverage-data

      - name: List directory contents after download
        run: ls -al

      - name: List directory contents after download
        run: |
          cd coverage-data
          ls -al

      - name: Debug coverage data before combining
        run: python -m coverage debug data

      - name: Debug - Check if .coverage exists
        run: test -f .coverage && echo ".coverage exists" || echo ".coverage does NOT exist"

      # - name: Debug - Show .coverage contents
      #   run: cat .coverage
      - name: Check number of coverage files
        id: check-num-files
        run: |
          cd coverage-data
          num_files=$(ls .coverage_* | wc -l)
          echo "::set-output name=num_files::$num_files"   
      # previously: python -m coverage combine ./.coverage  # specify the file
      - name: Combine coverage data
        if: steps.check-num-files.outputs.num_files > 1  
        run: |
          cd coverage-data
          python -m coverage combine .coverage_*

      - name: Generate HTML report
        run: |
          cd coverage-data
          ls -al
          python -m coverage html --skip-covered --skip-empty || echo "Coverage command failed"

      # Comment for debugging. Uncomment to fail if coverage is below 100%.
      # - name: Fail if coverage is below 100%
      #   run: python -m coverage report --fail-under=100

      # Do not need this as we arent combining coverage data.
      # - name: Debug coverage data after combining
      #   run: python -m coverage debug data

      - name: Upload HTML report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: htmlcov
